spring:
  # 업로드 파일 용령 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

  # MySQL 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Driver
    url: ${DB_URL}
    username: ${DB_USERNAME} # RDS 사용자 이름
    password: ${DB_PASSWORD} # RDS 사용자 비밀번호

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


  config:
    import:
      - s3bucket.yml

jwt:
  secret: 6eH@9fJ$2QwZ!8eX^4gT*7rA#5pL%1bK3uY8wE%2x